services:
  - type: web
    name: finai-backend
    runtime: python
    region: oregon
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: DATABASE_URL
        value: "postgresql://neondb_owner:npg_nmeBIQvh5uy8@ep-plain-surf-amyq24c9-pooler.c-5.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
